
spring.application.name=meetup

# h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DataSource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

jwt.secret = a01422a2d8f10d2754f748707e1685aa27d15a68fcf66bdf8aaa2b296eb832f89a76d00256732a582c9462edbb6b97e1df0c3c4d412eeb7572221c305d6d16fe